---
- name: Install dependencies
  tags: scripts
  package:
    name:
      - yt-dlp
      - fzf 
      - w3m
      - xsel
      - xclip
      - maim
      - xrectsel
      - byzanz
      - rlwrap

- name: Create symlinks for scripts
  tags: scripts
  shell: sudo stow -d "programs/scripts/" -t "/usr/local/bin" .

- name: Create symlinks for script share files
  tags: scripts
  shell: stow -d "share/scripts/" -t "$HOME/.local/share/" .
