---
- name: Install st
  tags: st
  shell: sudo rm programs/suckless/st/patches.h programs/suckless/st/config.h && make -C programs/suckless/st/ && sudo make install -C programs/suckless/st/

- name: Install dmenu
  tags: dmenu
  shell: sudo rm programs/suckless/dmenu/config.h && make -C programs/suckless/dmenu/ && sudo make install -C programs/suckless/dmenu/

- name: Install slstatus
  tags: slstatus
  shell: make -C $HOME/suckless/slstatus && make -C $HOME/suckless/slstatus/ clean install && if [ -f /usr/local/bin/slstatus ]; then sudo rm /usr/local/bin/slstatus; fi && sudo cp programs/suckless/slstatus/slstatus /usr/local/bin/

- name: Install dwm
  tags: dwm
  shell: make -C programs/suckless/dwm/ && sudo make install -C programs/suckless/dwm/
