---
- name: Check if rustup is installed
  tags: rust, langs
  shell: which rustup
  register: rustup_installed

- name: Install rustup
  tags: rust, langs
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  when: '"not found" in rustup_installed.stdout'

- name: Check if nightly channel is installed
  tags: rust, langs
  shell: rustup run nightly rustc --version
  register: nightly_channel_installed

- name: Install nightly channel
  tags: rust, langs
  shell: rustup toolchain install rustup
  when: '"error:" in nightly_channel_installed.stdout'

- name: Set nightly channel to default 
  tags: rust, langs
  shell: rustup default nightly

- name: Update rustup
  tags: rust, langs
  shell: rustup update

- name: Check if cargo-edit is installed
  tags: rust, langs
  shell: which cargo-add
  register: cargo_edit_installed

- name: Install cargo-edit
  tags: rust, langs
  shell: cargo install cargo-edit
  when: '"not found" in cargo_edit_installed.stdout'

- name: Check if rust-analyzer is installed
  tags: rust, langs
  shell: which rust-analyzer
  register: rust_analyzer_installed

- name: Install rust-analyzer
  tags: rust, langs
  shell: rustup +nightly component add rust-analyzer-preview
  when: not '"/rust-analyzer" in rust_analyzer_installed.stdout'

- name: Check if clang is installed
  tags: C, langs
  shell: which clang
  register: clang_installed

- name: Install clang
  tags: C, langs
  become: yes
  package:
    name: clang
  when: '"not found" in clang_installed.stdout'

- name: Install typescript, yarn, javascript, eslint, prettier, diagnostic-languageserver, nodejs
  tags: langs, webdev
  package:
    name:
      - nodejs-lts-gallium
      - eslint
      - diagnostic-languageserver
      - prettier
      - typescript
      - yarn
      - js78

- name: Check if typescript-language-server is installed
  tags: langs, webdev
  shell: which typescript-language-server
  register: tsserver_installed

- name: Install typescript-language-server
  tags: langs, webdev
  shell: sudo npm install -g typescript-language-server
  when: '"not found" in tsserver_installed.stdout'

- name: Install python, pip, pyright
  tags: python, langs
  package:
    name:
      - python
      - python-pip
      - pyright
