---
- hosts: localhost
  vars:
    source_key: ".ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    ssh_hosts: ".ssh/known_hosts"
    dest_ssh_hosts: "{{ lookup('env', 'HOME') }}/.ssh/known_hosts"
    ssh_config: ".ssh/config"
    dest_ssh_config: "{{ lookup('env', 'HOME') }}/.ssh/config"
    gh_hosts: ".ssh/hosts.yml"
    dest_gh_hosts: "{{ lookup('env', 'HOME') }}/.config/gh/hosts.yml"
  connection: local
  roles:
    - ssh
    - core
    - dotfiles
    - neovim
    - suckless # needs to be before scripts
    - scripts
    - terminal
    - media
    - wms
    - emacs
    - langs
    - tools
    - productivity

# TODO: install stack
# note: stack needs ncurses5-compat-libs on arch
