---
- name: Ensure .ssh directory exists.
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - ssh

- name: Install ssh key
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags:
    - dotfiles
    - ssh

- name: Install ssh key public
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644
  tags:
    - dotfiles
    - ssh

- name: Install ssh hosts
  copy:
    src: "{{ ssh_hosts }}"
    dest: "{{ dest_ssh_hosts }}"
    mode: 0600
  tags:
    - dotfiles
    - ssh

- name: Install ssh config
  copy:
    src: "{{ ssh_config }}"
    dest: "{{ dest_ssh_config }}"
    mode: 0600
  tags:
    - dotfiles
    - ssh

- name: Ensure gh directory exists.
  file:
    dest: "{{ dest_gh_hosts | dirname }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - ssh

- name: Install gh hosts
  copy:
    src: "{{ gh_hosts }}"
    dest: "{{ dest_gh_hosts }}"
    mode: 0600
  tags:
    - dotfiles
    - ssh
