#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           0

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config removal_adjustment      false

bspc config split_ratio          0.50

bspc rule -a Gimp desktop='^8' state=floating follow=on

~/.config/bspwm/masterlayout.sh &
bspc config external_rules_command  ~/.config/bspwm/external_rules.sh
