---
- name: Install terminal apps
  tags: terminal
  package:
    name:
      - rxvt-unicode
      - urxvt-perls
      - perl
      - tmux
      - lsd
      - wget
      - unrar
      - unzip
      - zsh
      - github-cli
      - z
      - xcompmgr
      - mlterm
      - so

- name: Create terminal_emulator file
  shell: echo st > $HOME/.local/share/terminal_emulator

- name: Change default shell to zsh
  tags: terminal
  shell: USER=$(whoami); sudo chsh --shell /bin/zsh $USER

- name: Check if oh-my-zsh is installed
  tags: terminal
  stat:
    path: "$HOME/.oh-my-zsh"
  register: oh_my_zsh_installed

- name: Install oh-my-zsh
  tags: terminal
  shell: sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: not oh_my_zsh_installed.stat.exists

- name: Install zsh-theme1
  tags: terminal
  copy: src="oh-my-zsh/kiku.zsh-theme" dest="$HOME/.oh-my-zsh/themes/kiku.zsh-theme"

- name: Install zsh-theme2
  tags: terminal
  copy: src="oh-my-zsh/kikusimple.zsh-theme" dest="$HOME/.oh-my-zsh/themes/kikusimple.zsh-theme"

- name: Check if .zshrc.pre-oh-my-zsh exists
  tags: terminal
  stat:
    path: "$HOME/.zshrc.pre-oh-my-zsh"
  register: zshrc_pre_installed

- name: Remove .zshrc.pre-oh-my-zsh
  tags: terminal
  shell: mv $HOME/.zshrc.pre-oh-my-zsh $HOME/.zshrc
  when: zshrc_pre_installed.stat.exists

- name: Copy fonts
  tags: terminal, font
  shell: sudo cp fonts/*.ttf -t /usr/share/fonts/TTF

- name: Check if Ubuntu Family is installed
  tags: terminal, font
  stat:
    path: "/usr/share/fonts/ubuntu"
  register: ubuntu_family_installed

- name: Install Ubuntu Family
  tags: terminal, font
  become: yes
  copy: src="./fonts/ubuntu" dest="/usr/share/fonts/ubuntu"
  when: not ubuntu_family_installed.stat.exists

- name: Cache fonts
  tags: terminal, font
  shell: fc-cache --force
