---
- name: Clone/Pull Neovim
  tags: neovim
  shell: if [ ! -d "$HOME/neovim" ]; then git clone --branch nightly https://github.com/neovim/neovim $HOME/neovim; else git -C $HOME/neovim pull origin master; fi

- name: Install tree-sitter, cmake
  tags: neovim
  package:
    name: 
    - tree-sitter
    - cmake

- name: Build Neovim
  tags: neovim
  shell: sudo make distclean -C $HOME/neovim && sudo make -j$(nproc) CMAKE_BUILD_TYPE=RelWithDebInfo -C $HOME/neovim && sudo make install -C ~/neovim

- name: Create Neovim vim symlink if not present
  tags: neovim
  shell: if [ ! -f /usr/local/bin/vim ]; then ln -s $(which nvim) /usr/local/bin/vim; fi

- name: Install Packer
  tags: neovim, packer
  shell: packer_path="$HOME/.local/share/nvim/site/pack/packer/start/packer.nvim"; clone_cmd="git clone --depth 1 https://github.com/wbthomason/packer.nvim"; if [ -d $packer_path ]; then rm -rf $packer_path && eval $clone_cmd $packer_path; else eval $clone_cmd $packer_path; fi
